[project]
name = "RPGLootFeed"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "certifi==2024.7.4",
  "charset-normalizer==3.3.2",
  "idna==3.8",
  "requests==2.32.5",
  "urllib3==2.6.2",
  "defusedxml>=0.7.1",
  "playwright>=1.51.0",
]
